# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Infernosim < Formula
  desc "Deterministic incident replay for backend systems"
  homepage "https://github.com/pranaysparihar/InfernoSIM"
  version "3.0.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/pranaysparihar/InfernoSIM/releases/download/v3.0.1/InfernoSIM_3.0.1_darwin_amd64.tar.gz"
      sha256 "85d2e5c6464f5278ce650645c932dba0ee73a2eeb1862546f9f8a9f49a650477"

      define_method(:install) do
        bin.install "InfernoSIM"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/pranaysparihar/InfernoSIM/releases/download/v3.0.1/InfernoSIM_3.0.1_darwin_arm64.tar.gz"
      sha256 "61716f0601c612fef29b210af49e10aecbda38f68259c18357acc4a136c083d8"

      define_method(:install) do
        bin.install "InfernoSIM"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/pranaysparihar/InfernoSIM/releases/download/v3.0.1/InfernoSIM_3.0.1_linux_amd64.tar.gz"
      sha256 "f9f15d557cff57f6b08efffe507bf90d70ee12b00b504e04b16f97d0805de9b5"
      define_method(:install) do
        bin.install "InfernoSIM"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/pranaysparihar/InfernoSIM/releases/download/v3.0.1/InfernoSIM_3.0.1_linux_arm64.tar.gz"
      sha256 "e77fc4a3ed5d66ef93ef5ea38042bb3da90c227ed13d1b17615197d75a0eeb24"
      define_method(:install) do
        bin.install "InfernoSIM"
      end
    end
  end
end
